"""Explore: search ranking, citation discipline, and the guided walk's order.

Everything here is the pure half -- no database, no Chroma, no key. The parts
that need a live index are exercised in `tests/integration/test_explore_api.py`;
what is pinned here is the logic that decides *what an answer is allowed to say*,
which is where the damage lives.
"""

from __future__ import annotations

import uuid

from app.ingestion.summarise import NodeBrief, render_briefs
from app.llm.base import LLMRole
from app.llm.fake_provider import FakeLLMClient
from app.models import Chunk, SkillNode
from app.services.path_service import contracted_prereqs
from app.services.qa_service import absorb_citations, render_passages
from app.services.search_service import snippet_for, title_score

DUALITY_TEXT = (
    "Weak duality bounds the primal objective below by every feasible dual solution. "
    "The bound is attained exactly at optimality, which is strong duality."
)


def node(slug: str, title: str, *, assessable: bool = True, chunks: tuple[uuid.UUID, ...] = ()) -> SkillNode:
    return SkillNode(
        id=uuid.uuid4(),
        course_id=uuid.uuid4(),
        slug=slug,
        title=title,
        summary=f"{title}, as the book presents it.",
        assessable=assessable,
        source_chunk_ids=list(chunks),
        depth=0,
        difficulty=3,
    )


def chunk(text: str, *, page: int = 10, path: str | None = "5 / 5.2") -> Chunk:
    return Chunk(
        id=uuid.uuid4(),
        document_id=uuid.uuid4(),
        course_id=uuid.uuid4(),
        ordinal=0,
        page_start=page,
        page_end=page,
        section_path=path,
        text=text,
        token_count=len(text.split()),
        content_sha256="0" * 64,
    )


# ── search ranking ────────────────────────────────────────────────────────


def test_an_acronym_finds_its_node() -> None:
    """The case the semantic matcher cannot serve. "kkt" is three letters in an
    800-token chunk and a rounding error in that chunk's vector, but it is most
    of one node's name."""
    assert title_score("kkt", "The KKT Theorem", "the-kkt-theorem") > 0.8


def test_title_scoring_is_banded_by_how_exact_the_match_is() -> None:
    exact = title_score("weak duality", "Weak Duality", "weak-duality")
    prefix = title_score("weak", "Weak Duality", "weak-duality")
    inside = title_score("duality", "Weak Duality", "weak-duality")
    assert exact == 1.0
    assert exact > prefix > inside > 0


def test_a_typo_still_matches_but_ranks_below_a_real_one() -> None:
    typo = title_score("dulaity", "Weak Duality", "weak-duality")
    assert 0 < typo < title_score("duality", "Weak Duality", "weak-duality")


def test_an_unrelated_query_scores_zero() -> None:
    assert title_score("photosynthesis", "Weak Duality", "weak-duality") == 0.0


def test_a_slug_is_matched_as_words_not_as_a_slug() -> None:
    """A learner types "cutting planes", never "cutting-planes"."""
    assert title_score("cutting planes", "Cutting Planes", "cutting-planes") == 1.0


def test_a_snippet_is_cut_around_the_query_not_off_the_top() -> None:
    """A hit deep inside a chunk is otherwise represented by the chunk's opening,
    which does not show the user why it matched."""
    text = "Padding. " * 40 + "The cone of tight constraints is generated by the active rows."
    found = snippet_for("tight constraints", text, limit=80)
    assert "tight constraints" in found
    assert found.startswith("…")


def test_a_snippet_falls_back_to_the_opening_when_nothing_occurs() -> None:
    found = snippet_for("photosynthesis", DUALITY_TEXT, limit=40)
    assert found.startswith("Weak duality bounds")


def test_a_neighbour_is_not_a_match() -> None:
    """A vector index returns the k NEAREST chunks, never the k relevant ones.
    Without a floor, searching a course for "zzzz" came back with the entire
    tree at score 0.0 -- every node that owns a chunk, ranked by nothing."""
    from app.vector.base import VectorHit

    class Nearest:
        def query(self, course_id: str, embedding: list[float], k: int = 5) -> list[VectorHit]:
            return [VectorHit(chunk_id=str(uuid.uuid4()), score=score, metadata={}) for score in (0.0, 0.02, 0.9)]

    import app.services.search_service as service

    kept, reachable = _hits_with(service, Nearest())
    assert reachable is True
    assert len(kept) == 1, "only the chunk that was actually close survives"


def _hits_with(service, store) -> tuple[dict, bool]:
    """Call `_semantic_hits` against a stand-in index, with no Chroma and no key."""
    real_store, real_embed = service.get_vector_store, service.embed_texts_recorded
    service.get_vector_store = lambda: store
    service.embed_texts_recorded = lambda texts, course_id: [[0.0]]
    try:
        return service._semantic_hits(uuid.uuid4(), "anything")
    finally:
        service.get_vector_store, service.embed_texts_recorded = real_store, real_embed


# ── ask: the citation filter ──────────────────────────────────────────────


def passages() -> list[tuple[SkillNode, Chunk]]:
    first, second = chunk(DUALITY_TEXT), chunk("A basis is a set of columns whose submatrix is invertible.")
    return [(node("weak-duality", "Weak Duality"), first), (node("basis", "Basis"), second)]


def test_a_citation_naming_a_passage_that_was_never_shown_is_dropped() -> None:
    """The closed-vocabulary rule `prereqs._absorb` applies to edges, applied to
    citations. A citation the UI cannot resolve to an orb is not a citation."""
    shown = passages()
    kept = absorb_citations(
        [{"node_id": str(uuid.uuid4()), "chunk_id": str(shown[0][1].id), "quote": "Weak duality bounds"}],
        shown,
    )
    assert kept == []


def test_a_quote_that_is_not_in_the_passage_is_dropped() -> None:
    """The failure that makes RAG worse than no answer: a fluent, plausible,
    invented quotation attached to a real node id."""
    shown = passages()
    node_id, chunk_id = str(shown[0][0].id), str(shown[0][1].id)
    kept = absorb_citations(
        [{"node_id": node_id, "chunk_id": chunk_id, "quote": "Duality is a deep principle of convex analysis."}],
        shown,
    )
    assert kept == []


def test_a_verified_quote_survives_and_carries_its_source() -> None:
    shown = passages()
    kept = absorb_citations(
        [
            {
                "node_id": str(shown[0][0].id),
                "chunk_id": str(shown[0][1].id),
                "quote": "bounds the primal objective below",
            }
        ],
        shown,
    )
    assert len(kept) == 1
    assert kept[0].slug == "weak-duality"
    assert kept[0].source.page_start == 10


def test_a_quote_is_matched_with_whitespace_flattened() -> None:
    """A model reflows a quotation it copied out of a wrapped paragraph, and
    rejecting it for that would drop every citation from a real provider."""
    shown = passages()
    kept = absorb_citations(
        [
            {
                "node_id": str(shown[0][0].id),
                "chunk_id": str(shown[0][1].id),
                "quote": "bounds   the primal\n objective below",
            }
        ],
        shown,
    )
    assert len(kept) == 1


def test_the_same_passage_is_cited_once() -> None:
    shown = passages()
    item = {
        "node_id": str(shown[0][0].id),
        "chunk_id": str(shown[0][1].id),
        "quote": "attained exactly at optimality",
    }
    assert len(absorb_citations([item, item], shown)) == 1


async def test_the_fake_answers_from_the_rendering_the_prompt_actually_uses() -> None:
    """The fake reads back `render_passages`, not a hand-written shape, so a
    change to the wire format breaks a test rather than degrading an answer."""
    shown = passages()
    result = await FakeLLMClient().structured(
        LLMRole.COURSE_QA,
        {"book_title": "CO 250", "question": "what is weak duality?", "passages": render_passages(shown)},
    )

    kept = absorb_citations(result.data["citations"], shown)
    assert len(kept) == 1
    assert kept[0].slug == "weak-duality"


async def test_the_fake_refuses_when_no_passage_is_about_the_question() -> None:
    """A stand-in that always answered would make every grounding test vacuous."""
    result = await FakeLLMClient().structured(
        LLMRole.COURSE_QA,
        {"book_title": "CO 250", "question": "photosynthesis chloroplast", "passages": render_passages(passages())},
    )
    assert result.data["citations"] == []
    assert "does not cover" in result.data["answer"]


# ── node summaries through the seam ───────────────────────────────────────


async def test_the_fake_summariser_omits_a_node_its_excerpt_says_nothing_about() -> None:
    """Omission is the behaviour the prompt asks a real model for, and the
    fallback it protects: an omitted node keeps its deterministic caption."""
    briefs = [
        NodeBrief("weak-duality", "Weak Duality", DUALITY_TEXT),
        NodeBrief("the-kkt-theorem", "The KKT Theorem", "−3 −2 −1 1 2 3 2 4 6 8 x y epi(f) = y x"),
    ]
    result = await FakeLLMClient().structured(
        LLMRole.NODE_SUMMARY,
        {"book_title": "CO 250", "node_count": len(briefs), "nodes": render_briefs(briefs)},
    )

    assert {item["slug"] for item in result.data["summaries"]} == {"weak-duality"}


# ── the guided path ───────────────────────────────────────────────────────


def test_a_container_is_seen_through_rather_than_walked() -> None:
    """The transparency rule `gating_masteries` applies to locking, applied to
    ordering: dropping the chapter heading must not lose "duality before KKT"."""
    duality, weak, kkt = uuid.uuid4(), uuid.uuid4(), uuid.uuid4()
    prereqs = {weak: [duality], kkt: [weak], duality: []}
    assessable = {duality: False, weak: True, kkt: True}

    resolved = contracted_prereqs(prereqs, assessable)

    assert duality not in resolved, "a container is not a step"
    assert resolved[weak] == set(), "a container with no prerequisites gates nothing"
    assert resolved[kkt] == {weak}


def test_a_container_passes_its_own_prerequisites_through() -> None:
    """A chapter that genuinely sits behind real material still orders it."""
    basis, chapter, simplex = uuid.uuid4(), uuid.uuid4(), uuid.uuid4()
    prereqs = {chapter: [basis], simplex: [chapter]}
    assessable = {basis: True, chapter: False, simplex: True}

    assert contracted_prereqs(prereqs, assessable)[simplex] == {basis}


def test_a_cycle_of_containers_terminates_without_a_self_edge() -> None:
    """Reading rows from a database, so a corrupt one must degrade rather than
    hang the request -- and must not hand `topological_depths` a self-edge,
    which it reports as the whole course being a cycle."""
    a, b, c = uuid.uuid4(), uuid.uuid4(), uuid.uuid4()
    prereqs = {b: [a], c: [b], a: [c]}
    assessable = {a: False, b: False, c: True}

    assert contracted_prereqs(prereqs, assessable)[c] == set()
