"""initial schema

Revision ID: 52cedf09cf10
Revises: 
Create Date: 2026-08-08 15:41:34.518940
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '52cedf09cf10'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('total_exp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('graph_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'ingesting', 'ready', 'failed')", name=op.f('ck_courses_status_valid')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_courses_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_index(op.f('ix_courses_owner_id'), 'courses', ['owner_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=8), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('pdf', 'epub', 'html', 'text')", name=op.f('ck_documents_source_type_valid')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_documents_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('course_id', 'content_sha256', name='course_content')
    )
    op.create_index(op.f('ix_documents_course_id'), 'documents', ['course_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_id', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('prompt_sha256', sa.String(length=64), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ok','schema_error','provider_error','timeout','refusal')", name=op.f('ck_llm_calls_status_valid')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_llm_calls_course_id_courses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    op.create_index('ix_llm_calls_course_role', 'llm_calls', ['course_id', 'role'], unique=False)
    op.create_index('ix_llm_calls_fingerprint', 'llm_calls', ['request_fingerprint'], unique=False)
    op.create_table('skill_edge_rejections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('prereq_slug', sa.String(length=64), nullable=False),
    sa.Column('target_slug', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('cycle_path', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason IN ('self_loop','duplicate','unknown_node','low_confidence','cycle')", name=op.f('ck_skill_edge_rejections_reason_valid')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_skill_edge_rejections_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_edge_rejections'))
    )
    op.create_index(op.f('ix_skill_edge_rejections_course_id'), 'skill_edge_rejections', ['course_id'], unique=False)
    op.create_table('skill_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_terms', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('depth', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('assessable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('source_chunk_ids', postgresql.ARRAY(sa.Uuid()), server_default='{}', nullable=False),
    sa.Column('mention_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name=op.f('ck_skill_nodes_difficulty_range')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_skill_nodes_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_nodes')),
    sa.UniqueConstraint('course_id', 'slug', name='course_slug')
    )
    op.create_index(op.f('ix_skill_nodes_course_id'), 'skill_nodes', ['course_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('vector_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_chunks_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('document_id', 'ordinal', name='document_ordinal')
    )
    op.create_index('ix_chunks_course_id', 'chunks', ['course_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_pages_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'page_index', name=op.f('pk_document_pages'))
    )
    op.create_table('ingest_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('units_done', sa.Integer(), server_default='0', nullable=False),
    sa.Column('units_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stage_detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('celery_root_id', sa.String(length=64), nullable=True),
    sa.Column('pipeline_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("state IN ('queued','parsing','chunking','embedding','extracting','reducing','finalizing','succeeded','failed','cancelled')", name=op.f('ck_ingest_jobs_state_valid')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_ingest_jobs_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_ingest_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_ingest_jobs_idempotency_key'))
    )
    op.create_index('ix_ingest_jobs_course_state', 'ingest_jobs', ['course_id', 'state'], unique=False)
    op.create_table('node_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('exp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('level', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('mastery', sa.Float(), server_default='0', nullable=False),
    sa.Column('ease', sa.Float(), server_default='2.5', nullable=False),
    sa.Column('interval_days', sa.Float(), server_default='0', nullable=False),
    sa.Column('reps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lapses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ease >= 1.3', name=op.f('ck_node_progress_ease_floor')),
    sa.CheckConstraint('mastery BETWEEN 0 AND 1', name=op.f('ck_node_progress_mastery_range')),
    sa.ForeignKeyConstraint(['node_id'], ['skill_nodes.id'], name=op.f('fk_node_progress_node_id_skill_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_node_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'node_id', name=op.f('pk_node_progress'))
    )
    op.create_index('ix_node_progress_user_due', 'node_progress', ['user_id', 'due_at'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('question_type', sa.String(length=16), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('source_chunk_ids', postgresql.ARRAY(sa.Uuid()), server_default='{}', nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("question_type IN ('short_answer','mcq','cloze','code')", name=op.f('ck_questions_question_type_valid')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_questions_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['skill_nodes.id'], name=op.f('fk_questions_node_id_skill_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index('ix_questions_node_id', 'questions', ['node_id'], unique=False)
    op.create_table('skill_edges',
    sa.Column('prereq_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('support', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_reduced', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_skill_edges_confidence_range')),
    sa.CheckConstraint('prereq_id <> target_id', name=op.f('ck_skill_edges_no_self_loop')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_skill_edges_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prereq_id'], ['skill_nodes.id'], name=op.f('fk_skill_edges_prereq_id_skill_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['skill_nodes.id'], name=op.f('fk_skill_edges_target_id_skill_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prereq_id', 'target_id', name=op.f('pk_skill_edges'))
    )
    op.create_index('ix_skill_edges_course_id', 'skill_edges', ['course_id'], unique=False)
    op.create_index('ix_skill_edges_target_id', 'skill_edges', ['target_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='issued', nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('points_hit', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('points_missed', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('exp_awarded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rescue_bonus_applied', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('grade_llm_call_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('issued','graded','abandoned')", name=op.f('ck_attempts_status_valid')),
    sa.CheckConstraint("verdict IS NULL OR verdict IN ('correct','partial','incorrect')", name=op.f('ck_attempts_verdict_valid')),
    sa.CheckConstraint('score IS NULL OR (score BETWEEN 0 AND 1)', name=op.f('ck_attempts_score_range')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_attempts_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_llm_call_id'], ['llm_calls.id'], name=op.f('fk_attempts_grade_llm_call_id_llm_calls'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['skill_nodes.id'], name=op.f('fk_attempts_node_id_skill_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_attempts_question_id_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='user_idempotency')
    )
    op.create_index('ix_attempts_user_created', 'attempts', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_attempts_user_node', 'attempts', ['user_id', 'node_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attempts_user_node', table_name='attempts')
    op.drop_index('ix_attempts_user_created', table_name='attempts')
    op.drop_table('attempts')
    op.drop_index('ix_skill_edges_target_id', table_name='skill_edges')
    op.drop_index('ix_skill_edges_course_id', table_name='skill_edges')
    op.drop_table('skill_edges')
    op.drop_index('ix_questions_node_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_node_progress_user_due', table_name='node_progress')
    op.drop_table('node_progress')
    op.drop_index('ix_ingest_jobs_course_state', table_name='ingest_jobs')
    op.drop_table('ingest_jobs')
    op.drop_table('document_pages')
    op.drop_index('ix_chunks_course_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_skill_nodes_course_id'), table_name='skill_nodes')
    op.drop_table('skill_nodes')
    op.drop_index(op.f('ix_skill_edge_rejections_course_id'), table_name='skill_edge_rejections')
    op.drop_table('skill_edge_rejections')
    op.drop_index('ix_llm_calls_fingerprint', table_name='llm_calls')
    op.drop_index('ix_llm_calls_course_role', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_documents_course_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_courses_owner_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
