"""Live coaching sessions, utterances, and a cancelled ledger status.

Hand-written rather than autogenerated: autogenerate also wanted to rename two
unrelated constraints on `recordings` and `refresh_sessions`, and a migration
that quietly reshapes tables it was not asked about is how a deploy goes wrong
at 3am.

`coach_sessions.take_id` is the client-generated primary key. That is what makes
finalizing idempotent: a socket that drops and an HTTP fallback that retries
both carry the same take id, so they cannot produce two attempts or two EXP
awards.

Revision ID: f6a7b8c9d0e1
Revises: e5f6a7b8c9d0
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "f6a7b8c9d0e1"
down_revision = "e5f6a7b8c9d0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "coach_sessions",
        sa.Column("take_id", sa.Uuid(), primary_key=True),
        sa.Column(
            "practice_session_id",
            sa.Uuid(),
            sa.ForeignKey("practice_sessions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("course_id", sa.Uuid(), sa.ForeignKey("courses.id", ondelete="CASCADE"), nullable=False),
        sa.Column("exercise_id", sa.Uuid(), sa.ForeignKey("exercises.id", ondelete="RESTRICT"), nullable=False),
        sa.Column(
            "attempt_id",
            sa.Uuid(),
            sa.ForeignKey("performance_attempts.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("status", sa.String(16), nullable=False, server_default="active"),
        sa.Column("protocol_version", sa.String(16), nullable=False, server_default="coach.v1"),
        sa.Column("observed_note_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("utterance_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("suppressed_turn_count", sa.Integer(), nullable=False, server_default="0"),
        # Divergence telemetry: what the live matcher believed, kept next to the
        # attempt the batch scorer produced from the same notes.
        sa.Column("live_matched_note_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("live_missed_note_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("live_extra_note_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('active', 'finalized', 'abandoned')", name="coach_status_valid"),
    )
    op.create_index("ix_coach_sessions_user_id", "coach_sessions", ["user_id"])
    op.create_index("ix_coach_sessions_course_id", "coach_sessions", ["course_id"])
    op.create_index("ix_coach_sessions_exercise_id", "coach_sessions", ["exercise_id"])
    op.create_index("ix_coach_sessions_practice_session_id", "coach_sessions", ["practice_session_id"])

    op.create_table(
        "coach_utterances",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "take_id",
            sa.Uuid(),
            sa.ForeignKey("coach_sessions.take_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("cue", sa.String(32), nullable=False),
        sa.Column("severity", sa.String(16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False, server_default=""),
        sa.Column("provider", sa.String(32), nullable=False, server_default="deterministic"),
        sa.Column("voice_provider", sa.String(32), nullable=True),
        sa.Column("spoken_text", sa.Text(), nullable=False),
        sa.Column("cancelled", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("take_clock_seconds", sa.Float(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("take_id", "sequence", name="coach_utterance_sequence"),
    )
    op.create_index("ix_coach_utterances_take_id", "coach_utterances", ["take_id"])

    # A barge-in burned tokens and is a distinct outcome from success.
    op.drop_constraint("status_valid", "llm_calls", type_="check")
    op.create_check_constraint(
        "status_valid",
        "llm_calls",
        "status IN ('ok','schema_error','provider_error','timeout','refusal','cancelled')",
    )


def downgrade() -> None:
    op.drop_constraint("status_valid", "llm_calls", type_="check")
    op.create_check_constraint(
        "status_valid",
        "llm_calls",
        "status IN ('ok','schema_error','provider_error','timeout','refusal')",
    )
    op.drop_index("ix_coach_utterances_take_id", table_name="coach_utterances")
    op.drop_table("coach_utterances")
    for name in (
        "ix_coach_sessions_practice_session_id",
        "ix_coach_sessions_exercise_id",
        "ix_coach_sessions_course_id",
        "ix_coach_sessions_user_id",
    ):
        op.drop_index(name, table_name="coach_sessions")
    op.drop_table("coach_sessions")
