/**
 * How a published curriculum is recognised in backend/app/curricula/, shared by
 * the generator (scripts/build-curricula.ts) and the test that checks its output.
 *
 * @spec LAND-STORY-010
 */

export interface PublishedCurriculum {
  instrument: string;
  title: string;
  version: number;
  skillCount: number;
}

interface CurriculumFile {
  instrument?: unknown;
  title?: unknown;
  version?: unknown;
  concepts?: unknown;
}

/**
 * The published curricula among a directory's JSON files, by instrument name.
 * `catalogue.json` (shared skill definitions) and `*-source.json` (a textbook a
 * tree is compiled from) are not curricula and carry no `instrument`.
 */
export function publishedCurricula(
  files: Record<string, string>,
): PublishedCurriculum[] {
  const found: PublishedCurriculum[] = [];
  for (const [name, text] of Object.entries(files)) {
    const parsed = JSON.parse(text) as CurriculumFile;
    const isCurriculum =
      !name.endsWith("-source.json") &&
      typeof parsed.instrument === "string" &&
      typeof parsed.title === "string" &&
      typeof parsed.version === "number" &&
      parsed.version >= 1 &&
      Array.isArray(parsed.concepts);
    if (isCurriculum) {
      found.push({
        instrument: parsed.instrument as string,
        title: parsed.title as string,
        version: parsed.version as number,
        skillCount: (parsed.concepts as unknown[]).length,
      });
    }
  }
  return found.sort((a, b) => a.instrument.localeCompare(b.instrument));
}

export function renderCurriculaModule(
  curricula: PublishedCurriculum[],
): string {
  const rows = curricula
    .map(
      (c) =>
        `  { instrument: ${JSON.stringify(c.instrument)}, title: ${JSON.stringify(c.title)}, version: ${c.version}, skillCount: ${c.skillCount} },`,
    )
    .join("\n");
  return `// GENERATED by scripts/build-curricula.ts from backend/app/curricula/ — do not edit.
// Re-run \`npm run build:curricula\` when a curriculum is added or changed;
// lib/curricula.test.ts fails while this file is stale.
import type { PublishedCurriculum } from "@/lib/curriculaSource";

/** Every instrument that ships with a published, versioned curriculum. @spec LAND-STORY-010 */
export const PUBLISHED_CURRICULA: readonly PublishedCurriculum[] = [
${rows}
];
`;
}
