// GENERATED by scripts/build-curricula.ts from backend/app/curricula/ — do not edit.
// Re-run `npm run build:curricula` when a curriculum is added or changed;
// lib/curricula.test.ts fails while this file is stale.
import type { PublishedCurriculum } from "@/lib/curriculaSource";

/** Every instrument that ships with a published, versioned curriculum. @spec LAND-STORY-010 */
export const PUBLISHED_CURRICULA: readonly PublishedCurriculum[] = [
  { instrument: "banjo", title: "Banjo", version: 1, skillCount: 7 },
  {
    instrument: "drums",
    title: "Drum Kit Foundations",
    version: 1,
    skillCount: 9,
  },
  {
    instrument: "guitar",
    title: "Guitar Foundations",
    version: 1,
    skillCount: 10,
  },
  {
    instrument: "piano",
    title: "Piano Foundations",
    version: 1,
    skillCount: 11,
  },
  {
    instrument: "trumpet",
    title: "Trumpet Foundations",
    version: 1,
    skillCount: 8,
  },
  {
    instrument: "violin",
    title: "Violin Foundations",
    version: 1,
    skillCount: 8,
  },
];
